### ISSUE TITLE
Bug ntoes

### ISSUE THREAD

**Issue by spacewalkingninja** [DeSOTAai/DeRunner#1]
1: child models aren't tested when added to user.config.yaml and services.config.yaml is recreated
2: test file path naming should be talked abt

**Comment by franciscomvargas** [comment]
# Let's Go! First Issue C:

## child models aren't tested when added to user.config.yaml and services.config.yaml is recreated

To trigger model test you need to remove the desired model from `admissions`
![image](https://github.com/DeSOTAai/DeRunner/assets/87917356/8d64846a-f764-4f9a-9315-564a72d249df)


## test file path naming should be talked abt

https://github.com/DeSOTAai/DeRunner/blob/ddf3f1c6c8ef9e97dcc4b62f46f585e5ad834e04/Tools/builtin_model_tester.py#L438
![maxresdefault](https://github.com/DeSOTAai/DeRunner/assets/87917356/c3cba1ec-4c74-4d5e-8ec4-dd6d753df163)
